[0m14:51:58.069915 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1107c2410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110811e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11082b210>]}


============================== 14:51:58.073930 | c00bf444-6329-4857-a783-814ead2735d1 ==============================
[0m14:51:58.073930 [info ] [MainThread]: Running with dbt=1.7.17
[0m14:51:58.074497 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/macbookair/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init marketingdbt', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:51:58.075650 [debug] [MainThread]: Starter project path: /Users/macbookair/opt/anaconda3/envs/dbtcourse/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:51:58.081188 [info ] [MainThread]: 
Your new dbt project "marketingdbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:51:58.081759 [info ] [MainThread]: Setting up your profile.
[0m14:54:53.045587 [info ] [MainThread]: Profile marketingdbt written to /Users/macbookair/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:54:53.109833 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 175.11383, "process_user_time": 3.423164, "process_kernel_time": 0.348876, "process_mem_max_rss": "158040064", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:54:53.112057 [debug] [MainThread]: Command `dbt init` succeeded at 14:54:53.111233 after 175.12 seconds
[0m14:54:53.113885 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11082a950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11082a190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110829e50>]}
[0m14:54:53.115358 [debug] [MainThread]: Flushing usage events
[0m14:55:05.666245 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1104e08d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1104f2410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1104f2c50>]}


============================== 14:55:05.670161 | 901864ec-19e5-46f7-8f7a-1dfd56ed05c4 ==============================
[0m14:55:05.670161 [info ] [MainThread]: Running with dbt=1.7.17
[0m14:55:05.670709 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/macbookair/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:55:05.671348 [info ] [MainThread]: dbt version: 1.7.17
[0m14:55:05.671658 [info ] [MainThread]: python version: 3.11.9
[0m14:55:05.671960 [info ] [MainThread]: python path: /Users/macbookair/opt/anaconda3/envs/dbtcourse/bin/python
[0m14:55:05.672248 [info ] [MainThread]: os info: macOS-10.16-x86_64-i386-64bit
[0m14:55:05.678344 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.redshift'
[0m14:55:06.413271 [info ] [MainThread]: Using profiles dir at /Users/macbookair/.dbt
[0m14:55:06.413710 [info ] [MainThread]: Using profiles.yml file at /Users/macbookair/.dbt/profiles.yml
[0m14:55:06.414031 [info ] [MainThread]: Using dbt_project.yml file at /Users/macbookair/dbtmarketing/marketingdbt/dbt_project.yml
[0m14:55:06.414328 [info ] [MainThread]: Configuration:
[0m14:55:06.414656 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m14:55:06.414970 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:55:06.415263 [info ] [MainThread]: Required dependencies:
[0m14:55:06.415591 [debug] [MainThread]: Executing "git --help"
[0m14:55:06.475179 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone             Clone a repository into a new directory\n   init              Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add               Add file contents to the index\n   mv                Move or rename a file, a directory, or a symlink\n   restore           Restore working tree files\n   rm                Remove files from the working tree and from the index\n   sparse-checkout   Initialize and modify the sparse-checkout\n\nexamine the history and state (see also: git help revisions)\n   bisect            Use binary search to find the commit that introduced a bug\n   diff              Show changes between commits, commit and working tree, etc\n   grep              Print lines matching a pattern\n   log               Show commit logs\n   show              Show various types of objects\n   status            Show the working tree status\n\ngrow, mark and tweak your common history\n   branch            List, create, or delete branches\n   commit            Record changes to the repository\n   merge             Join two or more development histories together\n   rebase            Reapply commits on top of another base tip\n   reset             Reset current HEAD to the specified state\n   switch            Switch branches\n   tag               Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch             Download objects and refs from another repository\n   pull              Fetch from and integrate with another repository or a local branch\n   push              Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m14:55:06.476106 [debug] [MainThread]: STDERR: "b''"
[0m14:55:06.476515 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m14:55:06.476863 [info ] [MainThread]: Connection test skipped since no profile was found
[0m14:55:06.477224 [info ] [MainThread]: [31m2 checks failed:[0m
[0m14:55:06.477529 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_redshift_dw", target "dev" invalid: Runtime Error
    Could not find adapter type redshift!


[0m14:55:06.477870 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/macbookair/dbtmarketing/marketingdbt/dbt_project.yml> not found

[0m14:55:06.480907 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.8782174, "process_user_time": 3.387906, "process_kernel_time": 0.289612, "process_mem_max_rss": "163766272", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:55:06.481847 [debug] [MainThread]: Command `dbt debug` failed at 14:55:06.481489 after 0.88 seconds
[0m14:55:06.482390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110506d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b7bf8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1104f1490>]}
[0m14:55:06.482918 [debug] [MainThread]: Flushing usage events
[0m14:56:32.805587 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112416f50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112470950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11248afd0>]}


============================== 14:56:32.809948 | c8d7b4b4-8b5b-44a6-a5fa-90d5d7883433 ==============================
[0m14:56:32.809948 [info ] [MainThread]: Running with dbt=1.7.17
[0m14:56:32.810490 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/macbookair/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:56:32.811121 [info ] [MainThread]: dbt version: 1.7.17
[0m14:56:32.811436 [info ] [MainThread]: python version: 3.11.9
[0m14:56:32.811744 [info ] [MainThread]: python path: /Users/macbookair/opt/anaconda3/envs/dbtcourse/bin/python
[0m14:56:32.812031 [info ] [MainThread]: os info: macOS-10.16-x86_64-i386-64bit
[0m14:56:33.543015 [info ] [MainThread]: Using profiles dir at /Users/macbookair/.dbt
[0m14:56:33.543437 [info ] [MainThread]: Using profiles.yml file at /Users/macbookair/.dbt/profiles.yml
[0m14:56:33.543784 [info ] [MainThread]: Using dbt_project.yml file at /Users/macbookair/dbtmarketing/marketingdbt/dbt_project.yml
[0m14:56:33.544166 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:56:33.546746 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.80447054, "process_user_time": 3.392336, "process_kernel_time": 0.266517, "process_mem_max_rss": "163770368", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:56:33.547345 [debug] [MainThread]: Command `dbt debug` failed at 14:56:33.547089 after 0.81 seconds
[0m14:56:33.547688 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11248ad50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d68ef10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x130deb810>]}
[0m14:56:33.548013 [debug] [MainThread]: Flushing usage events
[0m15:24:19.990093 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ed012d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ed57490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ed57c90>]}


============================== 15:24:19.995729 | 7ebc38ce-475a-4706-850f-7fc9c4a6b13b ==============================
[0m15:24:19.995729 [info ] [MainThread]: Running with dbt=1.7.17
[0m15:24:19.996274 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/macbookair/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:24:19.996810 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/macbookair/dbtmarketing/marketingdbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:24:19.999296 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0739795, "process_user_time": 1.29205, "process_kernel_time": 0.145266, "process_mem_max_rss": "106250240", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:24:20.000088 [debug] [MainThread]: Command `dbt run` failed at 15:24:19.999760 after 0.07 seconds
[0m15:24:20.000495 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e15af50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d5f1510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ed4fb50>]}
[0m15:24:20.000852 [debug] [MainThread]: Flushing usage events
[0m14:23:40.121217 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f1a810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110fa9e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110fab810>]}


============================== 14:23:40.126896 | 0c1dd990-0b23-47d6-8168-750f205db119 ==============================
[0m14:23:40.126896 [info ] [MainThread]: Running with dbt=1.7.17
[0m14:23:40.127440 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/macbookair/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:23:40.127973 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/macbookair/dbtmarketing/marketingdbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:23:40.130128 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.069947794, "process_user_time": 1.281651, "process_kernel_time": 0.11663, "process_mem_max_rss": "106774528", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:23:40.130846 [debug] [MainThread]: Command `dbt run` failed at 14:23:40.130527 after 0.07 seconds
[0m14:23:40.131217 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1109a9fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110fb3090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c275310>]}
[0m14:23:40.131554 [debug] [MainThread]: Flushing usage events
